name: backend
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  uuid: ^4.5.1
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  lints: ^6.0.0
