// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaG105cjRhMZOHQNDmZ0axDVmvPfkSZCA',
    appId: '1:870560201688:web:0b3b0bb5b638599db450ad',
    messagingSenderId: '870560201688',
    projectId: 'book-store-sw2',
    authDomain: 'book-store-sw2.firebaseapp.com',
    storageBucket: 'book-store-sw2.firebasestorage.app',
    measurementId: 'G-4LMHECSP4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SOw_QLOER2l0EloYRpZy7NYhBj0d3JM',
    appId: '1:870560201688:android:1caf68ada5d70aa3b450ad',
    messagingSenderId: '870560201688',
    projectId: 'book-store-sw2',
    storageBucket: 'book-store-sw2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwHe9wJVorboucds0_DboIo8P6WYFUd_A',
    appId: '1:870560201688:ios:6d1b9bb7119da06db450ad',
    messagingSenderId: '870560201688',
    projectId: 'book-store-sw2',
    storageBucket: 'book-store-sw2.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwHe9wJVorboucds0_DboIo8P6WYFUd_A',
    appId: '1:870560201688:ios:6d1b9bb7119da06db450ad',
    messagingSenderId: '870560201688',
    projectId: 'book-store-sw2',
    storageBucket: 'book-store-sw2.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaG105cjRhMZOHQNDmZ0axDVmvPfkSZCA',
    appId: '1:870560201688:web:7f8dd445532830f4b450ad',
    messagingSenderId: '870560201688',
    projectId: 'book-store-sw2',
    authDomain: 'book-store-sw2.firebaseapp.com',
    storageBucket: 'book-store-sw2.firebasestorage.app',
    measurementId: 'G-Y6G8NYEWFC',
  );

}